name: build
on: [push]

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x.x'
      - uses: actions/cache@v1
        id: cache
        with:
          path: /usr/local/bin/opa
          key: ${{ runner.os }}-opa
      - name: Download opa
        if: steps.cache.outputs.cache-hit != 'true'
        uses: wei/wget@v1
        with:
          args: -O opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
      - name: Install opa
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo mv opa /usr/local/bin/ && sudo chmod +x /usr/local/bin/opa
      - name: Build plugin
        run: ./gradlew check shadowJar
      - name: Jacoco test report
        run: ./gradlew jacocoTestReport
      - uses: actions/upload-artifact@v1
        with:
          name: opa-authorizer
          path: build/libs
      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          name: opa-kafka-plugin

